version: "3"

services:
  bitstamp_binance_dashboard:
    build:
      context: .
    image: makevoid/bitstamp_binance_dashboard
    ports:
      - 3000:3000
    environment:
      - DOCKER=1
      - RACK_ENV=production
      - AUTH_PASSWORD
      - BINANCE_API_KEY
      - BINANCE_SECRET_KEY
      - BITSTAMP_API_KEY
      - BITSTAMP_API_SECRET
      - BITSTAMP_CLIENT_ID
